### ISSUE TITLE
RuntimeError Problem

### ISSUE THREAD

**Issue by christophyoon** [ANLGBOY/WaveNODE#1]
Hello, 

First of all, thank you for sharing your work on Github.

I am currently studying a compressed flow-based neural vocoder. 

I would like to train your model but I have encountered the following problem:

Traceback (most recent call last):
File "train.py", line 280, in <module>
training_epoch_loss = train(epoch, model, optimizer, scheduler, log_train, args)
File "train.py", line 71, in train
loss.backward()
File "/home/prml/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/home/prml/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in
backward
allow_unreachable=True)  # allow_unreachable flag
RuntimeError: If using tupled rtol it must have the same length as the tuple y0

I tried to debug the error but couldn't find any related problems in google.

Are you familiar with this issue?

All I've changed is data_path and model_name. I didn't change anything else.

My workspace is:
PyTorch 1.6.0
Python 3.7.3

Please Help.

Thank you

**Comment by ANLGBOY** [comment]
We checked the code again but couldn't find any problem. The shapes of input to the model are x: [20, 1, 15872] and c: [20, 80, 62]. Are these same for your code?

**Comment by christophyoon** [comment]
Yes, I printed out x, and c and shapes are exactly the same.

I think I might find the source of the issue if I figure what are rtol and y0....

I'm not familiar with rtol... Do you know anything about it?

**Comment by ANLGBOY** [comment]
'rtol' and 'atol' are tolerance parameters used in a ODE solver. 
I guess you can try changing 'atol=[self.atol, self.atol, self.atol]' to 'atol=self.atol' in layers.py (as well as rtol).
Also, here's the FAQ about torchdiffeq: https://github.com/rtqichen/torchdiffeq/blob/master/FAQ.md

**Comment by christophyoon** [comment]
Ok, so the training works after i changed both list of atol and rtol to single self.atol and self.rtol. Guess it automatically broadcast to y0?

But as you defined rtol [self.rtol, self.rtol, **self.atol**].... Would this cause any problem?

**Comment by ANLGBOY** [comment]
That's my mistake(typo). I'll correct it soon :)

**Comment by christophyoon** [comment]
Thanks for the help!
